# Generated by Django 4.0.3 on 2023-08-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rokkr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mapplayed', models.CharField(max_length=25)),
                ('opponent', models.CharField(max_length=3)),
                ('p1', models.FloatField()),
                ('p2', models.FloatField()),
                ('p3', models.FloatField()),
                ('p4', models.FloatField()),
                ('p5', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
